### ISSUE TITLE
New Resource

### ISSUE THREAD

**Issue by gsimone** [snipcart/learn-vanilla-js#1]
Hey, opening an issue before an eventual PR. I found this resource https://www.robinwieruch.de/javascript-fundamentals-react-requirements/, it's about JS fundamentals for React developers, let me know if it's something that could be added 👍

**Comment by thefln** [comment]
@gsimone this is a solid piece indeed. I'll be adding a "Noteworthy articles ✍️" section soon to the repo (or you can do it with your PR if you'd like!) . This will be a perfect fit.
