### ISSUE TITLE
TodoMVC Todo List TDD Example/Tutorial: Course or Resource?

### ISSUE THREAD

**Issue by nelsonic** [snipcart/learn-vanilla-js#7]
Hi @thefln, @thatfrankdev & friends @snipcart! 👋 
Thank you for the great resource list for VanillaJS and superb blog post! 🎉 
(_I've found myself linking to / sharing it on many occasions!_)

I would like to propose an addition:
https://github.com/dwyl/todomvc-vanilla-javascript-elm-architecture-example
It's a step-by-step tutorial of creating a TodoMVC Todo List App using nothing but VanillaJS + HTML.
The Elm Architecture is used to organise the code but no dependencies are included.

I don't know if this belongs in **Courses** or "**Evergreen resources**" given that it's a complete start-to-finish lesson on building a Todo List App it could be considered a "course" ...

Please let me know your thoughts. I will PR the addition, just want your thoughts on _where_ it belongs.
Thanks in advance! ✨

**Comment by thefln** [comment]
@nelsonic sorry for the late reply here! Awesome resource. Would you mind adding it to "Course" with a PR? Also, the guys on the team all love what you're doing at dwyl. 👍

**Comment by nelsonic** [comment]
@thefln thanks! Stoked you like it. preparing PR now ... 🚧  🍅 ⏳

**Comment by nelsonic** [comment]
PR: #8 (_thanks!_) :shipit: 
also no need to apologise, I know you're busy building a **_sick_ product**! 🎉 
hope you have a _great_ weekend! ☀️
